Play nice with existing virtual environments, gcloud plugin now broken

diff --git a/rc/shell_functions b/rc/shell_functions
--- a/rc/shell_functions
+++ b/rc/shell_functions
@@ -27,7 +27,12 @@ function realpath() {
 }
 
 function resolve_ip() {
-    host $1 | tail -1 | awk '{print $NF}'
+    local result=$(host $1 | tail -1 | awk '{print $NF}')
+    if [ "$result" = "3(NXDOMAIN)" ]; then
+      echo "Host $1 not found" 1>&2
+      return 1
+    fi
+    echo $result
 }
 
 case $OSTYPE in
